version: '2'
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  web:
    build:
      context: .
    depends_on:
      - mongo
    links:
      - mongo
    ports:
      - "8082:8082"
    command: npm run start

